### ISSUE TITLE
关于近代物理实验（APL）的后续计划

### ISSUE THREAD

**Issue by pifuyuini** [TaLEsCuber/APLabR_TaLEs#9]
### 该写下一个实验的预习报告了！

**_实验征程浩瀚，科学星辰璀璨。吾辈科研人，肩负重任，同心协力，定能拨开迷雾，揭开自然之谜。实验虽艰辛，成果定辉煌，让我们携手并肩，共创科研新篇章！_**

> 鉴于实验进展的紧迫性，恳请您能尽快安排后续实验的相关事宜，以便我们能更有效地推进项目，取得突破性的成果。感谢您的积极配合！

**Comment by TaLEsCuber** [comment]
D8的预习报告写完了。比较紧急的应该是下周的锁相的实验，这个貌似也是要提交预习报告的。
